name: walkietalkie
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.1
  firebase_core: ^1.7.2
  firebase_storage: ^3.4.0
  image_picker: ^0.8.6
  audioplayers: ^0.16.0
  path_provider: ^2.0.9
  flutter_sound: ^9.1.1
  bluetooth: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
